name:                grammar-of-graphics
version:             0.1.0.0
github:              "adamConnerSax/grammar-of-graphics/grammar-of-graphics"
license:             BSD3
author:              "Adam Conner-Sax"
maintainer:          "adam_conner_sax@yahoo.com"
copyright:           "2019 Adam Conner-Sax"

extra-source-files:
- Readme.md
- ChangeLog.md

synopsis:            Grammar-of-graphics types and combinators for building descriptions of data visualizations
category:            Graphics, Visualization

description:         Please see the README on GitHub at <https://github.com/adamConnerSax/grammar-of-graphics/grammar-of-graphics#readme>

dependencies:
- array >= 0.4.0.1 && <= 0.6.0.0
- base >= 4.7 && < 5
- containers >= 0.5.0.0 && <= 0.7.0.0
- foldl >= 1.4.0 && <= 1.5.0.0
- text >= 1.1.0.1 && < 1.3.0.0
- time >= 1.8 && <= 1.10.0

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies

flags:
  dump-core:
    description: Dump HTML for the core generated by GHC during compilation
    default:     False
    manual:      True

library:
  ghc-options: -O -Wall
  source-dirs: src

  when:
    - condition: flag(dump-core)
      dependencies:
        - dump-core
      ghc-options:
        - -fplugin=DumpCore
        - -fplugin-opt DumpCore:core-html

